language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src PLATFORMIO_BUILD_FLAGS="-D TRAVIS_CI"

install:
    - pip install -U platformio
    - platformio update
    - platformio lib -g install 89          # https://platformio.org/lib/show/89/PubSubClient
    - platformio lib -g install 64          # https://platformio.org/lib/show/64/ArduinoJson
    - platformio lib -g install 567         # https://platformio.org/lib/show/567/WifiManager

script:
    - platformio ci --board=esp01_1m